/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 30 13:28:11 GMT 2018
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class QualificationTest_getMin_Test extends QualificationTest_getMin_Test_scaffolding {

  //Test case number: 0
  /*
   * 2 covered goals:
   * Goal 1. QualificationTest.getMin(II)I: I26 Branch 3 IFNE L20 - false
   * Goal 2. QualificationTest.getMin(II)I: I29 Branch 4 IF_ICMPGT L20 - true
   */

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      QualificationTest qualificationTest0 = new QualificationTest();
      int int0 = qualificationTest0.getMin((-1), 852);
  }
}
