/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 27 12:07:40 GMT 2018
 */

package datastructures;

import org.junit.Test;
import static org.junit.Assert.*;
import datastructures.StackAr;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class StackAr_pop_Test extends StackAr_pop_Test_scaffolding {

  //Test case number: 0
  /*
   * 5 covered goals:
   * Goal 1. Strong Mutation 5: datastructures.StackAr.pop()V:117 - InsertUnaryOp +1 (this.topOfStack:0,-1;)
   * Goal 2. Strong Mutation 7: datastructures.StackAr.pop()V:117 - ReplaceConstant - 1 -> 0 (this.topOfStack:0,-1;)
   * Goal 3. Strong Mutation 8: datastructures.StackAr.pop()V:117 - ReplaceArithmeticOperator - -> + (this.topOfStack:1,-1;)
   * Goal 4. Strong Mutation 9: datastructures.StackAr.pop()V:117 - ReplaceArithmeticOperator - -> % (this.topOfStack:0,-1;)
   * Goal 5. Strong Mutation 10: datastructures.StackAr.pop()V:117 - ReplaceArithmeticOperator - -> * (this.topOfStack:0,-1;)
   */

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      StackAr stackAr0 = new StackAr();
      Object object0 = new Object();
      stackAr0.push(object0);
      stackAr0.pop();
  }

  //Test case number: 1
  /*
   * 1 covered goal:
   * Goal 1. Strong Mutation 3: datastructures.StackAr.pop()V:116 - InsertUnaryOp -1 (this.theArray;)
   */

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      StackAr stackAr0 = new StackAr();
      Object object0 = new Object();
      stackAr0.push(object0);
      stackAr0.push((Object) null);
      stackAr0.pop();
      Object object1 = stackAr0.top();
  }
}
