/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 27 10:04:37 GMT 2018
 */

package datastructures;

import org.junit.Test;
import static org.junit.Assert.*;
import datastructures.StackAr;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class StackAr_top_Test extends StackAr_top_Test_scaffolding {

  //Test case number: 0
  /*
   * 2 covered goals:
   * Goal 1. datastructures.StackAr.top()Ljava/lang/Object;: I58 Branch 7 IFNE L77 - false
   * Goal 2. datastructures.StackAr.top()Ljava/lang/Object;: I61 Branch 8 IF_ICMPGT L77 - true
   */

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      StackAr stackAr0 = new StackAr();
      stackAr0.push((Object) null);
      Object object0 = stackAr0.top();
  }
}
